### ISSUE TITLE
Sync definition

### ISSUE THREAD

**Issue by EthraZa** [lukasz-wronski/vscode-ftp-sync#10]
Related to #5 (Topic 5)

The senario:
We both download files 1.js and 2.js from server. Now, you edit file 1.js and upload it to the server, then I edit file 2.js, but I have uploadOnSave:false. Now I need to send it over to the server. 

What to think about:
If I think about to Sync-L2R I guess the code will notice my files 1.js and 2.js are different from server, so it may upload both of then an overwrite your work on file 1.js. I did not tested it, but if it is what will happen, I would say it is not a "full-sync", but an "upload what diffs".

What if a full-sync:
In this example, what I would expect from a full-sync, is that it notice that the 1.js diffs from server, but the one on server is newer so it needs to be downloaded, so it would appear in the array of filesToDownload (or something) while the 2.js that diffs too but is newer on local, would show on the array filesToUpload of transaction json.

So:
If it is possible for the plugin to compare files mdate, that would make it possible to change Sync-L2R and Sync-R2L to just one "Sync".
Of course Force Upload and Force Download is good to keep, this guys just FTPing files without checking, what is way faster when you know what needs to be transfered and in what direction (probably most of the time we know).

**Comment by lukasz-wronski** [comment]
Yeah, what you looking for is more of a version controll sytem and as you mentioned in the other ticket it can be achived by integrating this plugin with git-ftp. I'll add this to the future plans.
