### ISSUE TITLE
Version 0.3.2 is not on the marketplace

### ISSUE THREAD

**Issue by michalhudecek** [lukasz-wronski/vscode-ftp-sync#100]
Good job with the latest updates! I am really glad that things are moving with this awesome extension. I just saw that the latest version in the repo is 0.3.2 but on the marketplace is 0.3.1. When will it be updated?

**Comment by lukasz-wronski** [comment]
@hajekj are we ready to release, or are you planning to include some more PR's to 0.3.2?

**Comment by hajekj** [comment]
@lukasz-wronski It should be good to publish. I suggest you test it before releasing v0.3.2 to the marketplace yourself as well for QA.

**Comment by trashbytes** [comment]
Any ETA on when this will be published?

**Comment by Apollon77** [comment]
I would also be interested in 0.3.2 on marketplace or a manual install way

**Comment by trashbytes** [comment]
@Apollon77 you can manually install this version by overwriting the installed one with the github files.

**Comment by lukasz-wronski** [comment]
Published - sorry for delay. I do not have time to maintain this plugin right now - @hajekj, can you let me know how can I allow you to use `vsce` tool and publish new versions of the plugin?
