### ISSUE TITLE
Got sync prepare in progress

### ISSUE THREAD

**Issue by stefanofiorentino** [lukasz-wronski/vscode-ftp-sync#11]
Hi, I'm working with a remote raspberry pi and I have this configuration file over SFTP:

```
{
    "remotePath": "/home/pi/devel",
    "host": "192.168.1.2",
    "username": "pi",
    "password": "raspberry",
    "port": 22,
    "uploadOnSave": false,
    "ignore": [
        "\\.vscode",
        "\\.git"
    ]
}
```

How can I overtake this issue? Thanks!

**Comment by lukasz-wronski** [comment]
What plugin version do you have?

**Comment by stefanofiorentino** [comment]
I have the 0.2.0, may be a configuration issue?

**Comment by lukasz-wronski** [comment]
@stefanofiorentino As far as I can see you are trying to connect to port `22`which is ssh. You should point to port `21` for FTP. Or you have unusual port configuration there?

**Comment by stefanofiorentino** [comment]
I need to connect to SFTP (FTP over SSH), have you tried?

2015-12-09 19:05 GMT+01:00 lukasz-wronski <notifications@github.com>:

> @stefanofiorentino <https://github.com/stefanofiorentino> As far as I can
> see you are trying to connect to port 22which is ssh. You should point to
> port 21 for FTP. Or you have unusual port configuration there?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lukasz-wronski/vscode-ftp-sync/issues/11#issuecomment-163342533>
> .
>



-- 
Ing. Stefano Fiorentino
Cell. +39 340 2216385

**Comment by lukasz-wronski** [comment]
The plugin supports FTP only, not sftp. I will add sftp support to future plans.
