### ISSUE TITLE
Prompt for password

### ISSUE THREAD

**Issue by danielsig727** [lukasz-wronski/vscode-ftp-sync#110]
A nice enhancement would be adding an option to let users don't need to store password in the config file.
Instead, users will be asked for password on the first connection every session.

**Comment by jasonsavard** [comment]
I agree, I use this option with FileZilla and it works well.

**Comment by hajekj** [comment]
Closed by #199

**Comment by jasonsavard** [comment]
@hajekj Fantastic work thanks for developing this feature. When will this be pushed to the ftp-sync extension in VS Code Marketplace? It seems it's still on v0.3.3 and doesn't yet contain this update.
