### ISSUE TITLE
Unable to commit changes after review

### ISSUE THREAD

**Issue by mirao** [lukasz-wronski/vscode-ftp-sync#112]
**Steps:**
- Make some local changes
- Ftp-sync: Remote to Local
- Review changes
- Ftp-sync: Commit

**Expected result:**
- changes are commited

**Actual result:**
- Warning: Command `workbench.files.action.closeFile` has been removed. You can use `workbench.action.closeActiveEditor` instead

**Used SW:**

- VScode 1.8.0, Windows 10/Ubuntu 16.10

**Comment by mirao** [comment]
![screenshot from 2016-12-20 19-36-49](https://cloud.githubusercontent.com/assets/12584138/21363810/694a67c4-c6ee-11e6-8af6-c812b478bb5d.png)
Screenshot of the issue

**Comment by ZanderBrown** [comment]
#79

**Comment by mirao** [comment]
Yes, it's working with ftp-sync 0.3.2. I got an update to 0.3.2 on both Win/Linux a few days ago.
