### ISSUE TITLE
Ftp-sync: Uploading **.php failed: Error: read ECONNRESET

### ISSUE THREAD

**Issue by monohe** [lukasz-wronski/vscode-ftp-sync#114]
The sync function worked well on my previous machine which was Windows 7. But after I switched to Windows 10 and installed VSC and FTP-sync. The sync function no longer works. No matter which ftp server I'm using.

**Comment by monohe** [comment]
forget the issue. I reinstalled the plugin and it works now. Sorry for bothering.

**Comment by MatthewGieger** [comment]
@hajekj  I believe this issue can be closed.
