### ISSUE TITLE
Save on second try

### ISSUE THREAD

**Issue by kasik96** [lukasz-wronski/vscode-ftp-sync#12]
Hi, i found little problem. I set auto-upload on FTP plugin. But it works on every second try. On first it only says Uploading, but never ends. And on second try, it works. Video explain it better: https://youtu.be/22Ecg4QSAe8

**Comment by lukasz-wronski** [comment]
@kasik96 It's fixed now. Try if it still occurs in 0.2.1.

**Comment by kasik96** [comment]
Now its says it Uploaded, but nothing really upload on server. And when i click on Local to Remote it says: Ftp-sync: sync error: Error: Use PORT or PASV first.
![screen shot 2015-12-09 at 21 33 44](https://cloud.githubusercontent.com/assets/7235992/11697961/b22757dc-9ebc-11e5-9f28-205fe79e9ca7.png)
And just stuck on this, when i click enter, it keep showing again.

**Comment by kasik96** [comment]
OK, i reinstall it, and just set it up again. And same thing. But when i se Local to Remote is says this:
![screen shot 2015-12-09 at 21 39 14](https://cloud.githubusercontent.com/assets/7235992/11698110/6a58bb20-9ebd-11e5-96c6-cb9b8d766031.png)
And this on auto-upload, but not every times, only sometimes.
![screen shot 2015-12-09 at 21 40 42](https://cloud.githubusercontent.com/assets/7235992/11698142/90435cd2-9ebd-11e5-8310-d9f03e999efa.png)
