### ISSUE TITLE
Timestamp in log messages

### ISSUE THREAD

**Issue by Export33** [lukasz-wronski/vscode-ftp-sync#121]
Hey,

can you pls add a timestamp to the log messages? It is hard to differtiate or see if the actual change is already uploaded.

[sync-helper] uploadFile
[sync-helper] connect
[sync-helper] uploadFile
[sync-helper] connect
[sync-helper] uploadFile

**Comment by c01nd01r** [comment]
+1. And some FinishUpload event would be nice...

**Comment by o-gh** [comment]
I want it too

**Comment by SynCap** [comment]
And name of file/folder is being processed.

**Comment by kalieye** [comment]
i changed the behaviour a bit, let me know if you have any thoughts about it, suggestions are more than welcome

**Comment by KamasamaK** [comment]
@kalieye Code looks good from what I can see, but still not deployed after 5 months.

**Comment by rsmolkin** [comment]
Have these changes gone out yet?  I'm still seeing the sync-helyper uploadFile and connect messages on every save.  Would like to disable those when it's working correctly, maybe just show one saying upload completed in the blue notification bar and not in the Output panel?
