### ISSUE TITLE
Ftp-sync: Selected file is ignored.

### ISSUE THREAD

**Issue by rico345100** [lukasz-wronski/vscode-ftp-sync#124]
Suddenly some files are not uploaded on save, so I tried upload manually, but it blocked and it saids:
> Ftp-sync: Selected file is ignored.

This is my ignore list in .vscode/ftp-sync.json

```json
{
...
  "ignore": [
        "\\.vscode",
        "\\.git",
        ".git",
		"node_modules",
		"dist",
        "\\.vscode",
        "\\.sass-cache",
		"\\node_modules",
        "\\dist"
    ]
}
```

A file that I am trying to upload is ./config/distributePolicy.json. I never told that ignore that file but why it happens? Also why I shouldn't upload manually? I need explanation. Thanks.

**Comment by robsonsobral** [comment]
Is your repository inside a folder with "git" on path? Remove the git rules from ignore array.

**Comment by onebeat** [comment]
I have the same problem and my .vscode ignore doesn't have anything....

**Comment by kuzdogan** [comment]
This also happens when you init an empty directory and choose `Browse Remote`. VSCode automatically selects a file inside the ignored `.vscode/` directory. Click outside or create an arbitrary file. 

Also what you want to do is probably to sync using `Remote to Local`.
