### ISSUE TITLE
Stuck at README.md...

### ISSUE THREAD

**Issue by dnviti** [lukasz-wronski/vscode-ftp-sync#127]
I'm now uploading my nodejs repo and it get stuck on that file inside node_modules.
This is my ignore:
`    "ignore": [
        "\\.vscode",
        "\\.git",
        "\\.DS_Store",
        "\\node-server\node_modules"
    ]`
Don't know why it still searches that directory, I've explicitly asked to ignore it...
![cattura](https://cloud.githubusercontent.com/assets/8649488/23043734/9cae74d4-f49d-11e6-95bd-1972a92ba134.PNG)

**Comment by ZanderBrown** [comment]
No you have explicitly told it to ignore:
```
\node-server
ode_modules
```

Because as you know \ is the escape character so unless it is escaped itself (as it the start of the line) it will escape whatever follows it in this case an 'n' meaning newline

**Comment by dnviti** [comment]
Ok! I was mistaken. Thank you!

**Comment by jsmilovic** [comment]
Thanks @ZanderBrown
