### ISSUE TITLE
Feature Idea: Upload .css files when updated with Sass or Less

### ISSUE THREAD

**Issue by nlxdodge** [lukasz-wronski/vscode-ftp-sync#128]
For instance:

If I use [Koala](http://koala-app.com/) to compile a .scss file to .css I have to save the file again.

So a feature that watches, if a file has changed to reupload the given file would be amazing. (Also when adding images you have to upload it by hand).

If I have some spare time I will fork the repo and try myself.

**Comment by jsmilovic** [comment]
@nlxdodge Pull request #118 resolved this, I have just gotten access to deploy this to the extension repository, so expect this to show up in the next day or so
