### ISSUE TITLE
Sync L2R does not work when it is a new folder

### ISSUE THREAD

**Issue by EthraZa** [lukasz-wronski/vscode-ftp-sync#13]
At least on ftp-sync 0.1.4:

1- Create a new folder, add a new file to it
2- Call Sync L2R (same happens with uploadOnSave)
3- [Error] Ftp-sync: Uploading tst.js failed: Error: 553 Can't open that file: No such file or directory

Can't test on ftp-sync 0.2.0 since it does not work at all for me.

**Comment by lukasz-wronski** [comment]
The sync mechanism was completely rewriten, so if you had such problem in FTP sync < 0.2.0 it's probably not a case in 0.2.0. I'm trying to find some time to fix the issues you've reported so far, so probably I'll do it in the next days.
