### ISSUE TITLE
How to Set keyboard shortcut for Upload Current File?

### ISSUE THREAD

**Issue by xttn** [lukasz-wronski/vscode-ftp-sync#130]
Hi, how do I set keyboard for upload current file to the hosting?
e.g. when i use `Alt+U` current file will upload to the host
// Bad support, uninstalled

**Comment by andremacola** [comment]
Had the same problem but I discovered a way.

In your key bindings

```
[
	{
        "key": "cmd+d",
        "command": "extension.ftpsyncsingle",
        "when": "editorTextFocus"
    }
]
```
