### ISSUE TITLE
prompt for sftp key password

### ISSUE THREAD

**Issue by pcause** [lukasz-wronski/vscode-ftp-sync#137]
It is really a bad idea to leave sftp key passwords lying around in various files.  can you make a change to prompt for the sftp key passphrase.

**Comment by ximarix** [comment]
This is actually really important! I use my private key for all sorts of things, it's not an option to just save the passphrase into the file. 
Before switching to vscode I was using sublime with sftp plugin. There it was working like pcause suggested. On first connect a prompt for the passphrase openend.

Any chance to implement this?

**Comment by Shulin** [comment]
Would also love this, because I don't like having my phrase stores in raw text.

**Comment by hajekj** [comment]
Closed by #199
