### ISSUE TITLE
"Upload file" on new local folder creates remote file (not folder)

### ISSUE THREAD

**Issue by bravo-kernel** [lukasz-wronski/vscode-ftp-sync#138]
Wonderful plugin. I did notice the following which seems like a bug:

1. Create a new local directory `woot` in Visual Studio Code

2. Right-mouse on folder `woot` in IDE

3. Select "Ftp-sync: File Upload"

**What happens:**  plugin creates a **file** called `woot` on remote server.

**Expected behavior:** plugin creates **directory** `woot` on remote server.

Creating an issue and not a PR since that's a bit above my `js` skillset atm. HTH

**Comment by providen-rob** [comment]
I also have this issue.

**Comment by kalieye** [comment]
i know it's not really a fix but i just committed a new version that disables the upload/download context menu item for folders, making the command compatible with syncing whole folders will require a bit of work but at least disabling the item will avoid useless file creation on the remote host

**Comment by bravo-kernel** [comment]
Fair enough @kalieye, I could see the effort required. Love your extension, keep up the good work!

**Comment by kalieye** [comment]
i actually put this on my todo list :) it's a very useful feature and will get added sooner or later!
thank you for your feedback
