### ISSUE TITLE
Suggestion: change "File Upload" context-item to "Upload"

### ISSUE THREAD

**Issue by bravo-kernel** [lukasz-wronski/vscode-ftp-sync#139]
I think the changing the context-item "File Upload" to simply "Upload" could improve usability as this would allow for both:

- uploading a directory (including content)
- uploading a file

Refs https://github.com/lukasz-wronski/vscode-ftp-sync/pull/92 and https://github.com/lukasz-wronski/vscode-ftp-sync/issues/53.

**Comment by daulet2030** [comment]
+1

**Comment by kalieye** [comment]
the menu item currently uploads only files (no support for directories yet) but as soon as we add the functionality the label will be replaced with the proper text
