### ISSUE TITLE
FTP sync on uploadOnSave - possible on gulp task?

### ISSUE THREAD

**Issue by vyskoczilova** [lukasz-wronski/vscode-ftp-sync#143]
Hi, is it possible to call the ftp-sync from Gulp? If I have a gulp task which generates style.css from style.scss file, the newely generated file style.css is not synced automatically, could I add it somehow to my gulp task?

**Comment by jareis** [comment]
Check ```generatedFiles``` option.

**Comment by vyskoczilova** [comment]
Thanks, I have missed it! It works fine, but sometimes it stops in middle off uploading generated css or map file and I need to restart it. Any ideas why? No error message given.
