### ISSUE TITLE
Generated File Watching #118? some problem

### ISSUE THREAD

**Issue by cocody** [lukasz-wronski/vscode-ftp-sync#144]
1. when I white "path": "" : then it will show me a error message

2. when the directory of compile file is "/public/pc/index.css". I need to white `"path": "/public"` rather than`"path": "/public/pc"` the second, it will error

3. I must be watch `app` and `public ` as the same time, but it not work when I try to white some like:  `"generatedFiles":  []`

**Comment by cocody** [comment]
OS: window 7
vscode: 1.10.2

"path": "/" is not work

**Comment by cocody** [comment]
problem 3 is solution by `"path": "/**"`

**Comment by jsmilovic** [comment]
Hm for #2 I have
```        "path": "/stylus/asdf",
```
and it works fine

**Comment by jsmilovic** [comment]
Sorry, 
        "path": "/stylus/asdf",
