### ISSUE TITLE
Downloadfile in contec menu

### ISSUE THREAD

**Issue by hazeem1991** [lukasz-wronski/vscode-ftp-sync#148]
i need to download a specified file not a hole folder from the server

**Comment by EthraZa** [comment]
Hi. I'm facing this "problem" right now. 
Right click on a file in Browser View shows the option "Ftp-sync: Upload File", but we already have Auto-upload on save, what would be really useful there is a "Ftp-sync: Download File" option.
For now, the only option I have is to Sync the folder Remote to Local, and sometimes it creeps me out hehe.

**Comment by LarsinYousif** [comment]
I created a PR to address this issue, hopefully it gets reviewed/accepted.

**Comment by kalieye** [comment]
merged, thank you!
