### ISSUE TITLE
extension.ftpsyncuploadselected failed

### ISSUE THREAD

**Issue by lu8aja** [lukasz-wronski/vscode-ftp-sync#151]
Hi,

I am finding trouble with this error, so far I was totally unable to get it to work, and I see that there had been similar cases before.

I am getting this cryptic error:
`Running the contributed command:'extension.ftpsyncuploadselected' failed.`

While using this config at projectfolder/.vscode/ftp-sync.json on Win7 to connect to Ubuntu over SSH:

```
{
    "remotePath": "/home/sites/www.XXXXX.com/web",
    "host": "10.0.0.1",
    "username": "myusername",
    "port": 22,
    "protocol": "sftp",
    "uploadOnSave": true,
    "debug": true,
    "privateKeyPath": "C:/Users/USER/.ssh/privkey",
    "ignore": 
        ".vscode",
        ".git",
        ".LOCAL",
        "*.tmp"
    ]
}
```

With other programs I have no issue with that privkey user, etc (For example Atom with remote-sync)
With ftp-sync I have no issues to other servers over FTP.

But so far I have been totally unable to use SFTP on ftp-sync

Something that might be relevant is that it fails immediately at once without any evidence of doing anything, neither outputting anything to any of the output windows.

Any help is gladly welcomed.

Regards!

**Comment by lu8aja** [comment]
Ok, I found the issue, I had a glob like searchn in the ignore, and this extension expects a regex.
Now, this really needs to tell you what's wrong when something goes wrong :)
Aside from that, great job.

**Comment by GeneralCan** [comment]
@lu8aja I'm having the same issue, how did you fix it?

**Comment by lu8aja** [comment]
This is not a valid regular expression:
"*.tmp"

You need instead something like ".*\\.tmp$"
Which translated the regular expression .*\.tmp$
Which matches anything ending in .tmp

**Comment by GeneralCan** [comment]
hmm, this is what I have, it looks correct to me though:
{
    "remotePath": "./_reports/",
    "host": "somehost.com",
    "username": "user",
    "password": "complicatedPassword",
    "port": 22,
    "secure": true,
    "protocol": "sftp",
    "uploadOnSave": true,
    "passive": false,
    "debug": false,
    "privateKeyPath": null,
    "passphrase": null,
    "ignore": [
        "\\.vscode",
        "\\.git",
        "\\.DS_Store"
    ],
    "generatedFiles": {
        "uploadOnSave": false,
        "extensionsToInclude": [],
        "path": ""
    }
}

**Comment by lu8aja** [comment]
Yeah, I don't see any problem related to what I said...
I think that the error is cryptic because it is a very high level catch, thus pretty much any error will end up with that message... I guess then it isn't the same case I experienced...

Now... you are connecting with SSH... however you don't have a privateKeyPath defined, could it be that?

**Comment by GeneralCan** [comment]
no, I can sync files already on the server, just can't upload new ones. 
I'll open a ticket since it seems to be a different issue. thanks for the help!

**Comment by lu8aja** [comment]
Yeah, better a separate one. YW! Good luck ;)
