### ISSUE TITLE
Automatically close panel when done with upload

### ISSUE THREAD

**Issue by maltepet** [lukasz-wronski/vscode-ftp-sync#153]
Is there a way to automatically close the panel when the upload is complete?

**Comment by hobbyman** [comment]
This panel only shows for the very first connection/upload. Any subsequent uploads/syncs the panel does not reappear. It would be nice if it never appeared on successful uploads/syncs. Maybe only ever show on error.

Btw, great extension, perfect for my workflow.

**Comment by kalieye** [comment]
i should have fixed it on my last commit, i made it so that if you put debug:false there are no debug messages, can you please try and confirm it it works for you? Cheers

**Comment by hobbyman** [comment]
Yes, debug is set to false. Just in case, here is what shows up in the **output** panel.
  
![snip20170508_7](https://cloud.githubusercontent.com/assets/883843/25800677/ea797852-33af-11e7-9606-3f50f76a0d75.png)

**Comment by kalieye** [comment]
oh i think you are using the version from vscode's extension, to see the new fixes you need to use the latest github tree

**Comment by NajSurf** [comment]
The latest version is now live on vscode marketplace.
