### ISSUE TITLE
FTP Passive Mode settings

### ISSUE THREAD

**Issue by suuuunto** [lukasz-wronski/vscode-ftp-sync#16]
He there, 

First of all, thanks for providing VSCode with that useful extension!

I got some problems with the ftp connection, which are related to passive mode settings. Would it be possible to add passive mode settings?

Thanks,
suuuunto

**Comment by lukasz-wronski** [comment]
@suuuunto: I've added a support for it and it will be available in 0.2.2 version, but I'd like to ask you to test it as I'm not sure how to do it. I'm sending "PASV" command after connection and server is responding "Entering passive mode". 

To use it add `"passive":true` to your ftp sync config file.

Version 0.2.2 should be available today.

**Comment by suuuunto** [comment]
Thanks, worked fine in my case!

**Comment by lukasz-wronski** [comment]
Thanks for feedback.
