### ISSUE TITLE
It would be nice to upload more than one file at a time. 

### ISSUE THREAD

**Issue by jcphlux** [lukasz-wronski/vscode-ftp-sync#160]
It would be nice to upload many files at a time. It would work like other standalone FTP clients.

**Comment by ZanderBrown** [comment]
But you can already do this?

**Comment by jcphlux** [comment]
Sweet... how? :)

**Comment by ZanderBrown** [comment]
Local to Remote sync

**Comment by jcphlux** [comment]
remote
