### ISSUE TITLE
Permission Denied Error when uploading main.css

### ISSUE THREAD

**Issue by rjnay1984** [lukasz-wronski/vscode-ftp-sync#161]
I'm constantly getting a permission denied error while running compass. When I save my sass file, and it compiles my css and tries to upload, I get the permission denied error. The weird thing is that sometimes it works, but most of the time it doesn't.

Here's my ftp-sync.json:

{
    "remotePath": "/",
    "host": "mysite.businesscatalyst.com",
    "username": "mysite.businesscatalyst.com/username",
    "password": "mypassword",
    "port": 22,
    "secure": false,
    "protocol": "sftp",
    "uploadOnSave": true,
    "passive": false,
    "debug": true,
    "privateKeyPath": null,
    "passphrase": null,
    "ignore": [
        "\\.vscode",
        "\\.git",
        "\\.DS_Store",
        "\\.sass-cache",
        ".gitignore",
        "README.md"
    ],
    "generatedFiles": {
        "uploadOnSave": true,
        "extensionsToInclude": [".scss" ,".css"],
        "path": "/stylesheets"
    }
}

**Comment by jareis** [comment]
The user don't have permissions to write to the root directory. 
I would recomend to check the paths with your sys admin.
