### ISSUE TITLE
Unable to commit when review sync.

### ISSUE THREAD

**Issue by menardany** [lukasz-wronski/vscode-ftp-sync#165]
When review sync, unable to commit.
Displays "Ftp-sync: no operations list to commit. Run sync first."

After searching in extension's modules, determined that it breaks at searching for `vscode.window.activeTextEditor.document.syncOptions`

Dany

**Comment by raitaionut** [comment]
Same issue here with "Ftp-sync: no operations list to commit. Run sync first."

**Comment by dcboy95** [comment]
Bump! same problem, after looking at the the sync summary page, doing the commit and getting "Ftp-sync: no operations list to commit. Run sync first."

**Comment by thewinger** [comment]
One more with the same issue

**Comment by juaniyyo** [comment]
One more with the same issue

**Comment by tonystz** [comment]
Is any way to resolve the issue?

**Comment by dcboy95** [comment]
Any updates on this?

**Comment by Landver** [comment]
the same issue,
my FTP-Sync config:
```
{
    "remotePath": "/blabla",
    "host": "1.1.1.1",
    "username": "blabla",
    "password": "blabla",
    "port": 22,
    "secure": true,
    "protocol": "sftp",
    "uploadOnSave": true,
    "passive": false,
    "debug": false,
    "privateKeyPath": null,
    "passphrase": null,
    "ignore": [
        "\\.vscode",
        "\\.git",
        "\\.DS_Store",
        "\\__pycache__",
        "\\migrations",
        "\\staticfiles",
        "\\celerybeat.pid"
    ],
    "generatedFiles": {
        "uploadOnSave": false,
        "extensionsToInclude": [],
        "path": ""
    }
}
```

**Comment by sstoychev** [comment]
One more with the same issue

**Comment by rahulnever2far** [comment]
I'm facing the same issue.

**Comment by XiaoQiJun** [comment]
One more with the same issue.

**Comment by tzimpel** [comment]
One more with the same issue.

**Comment by black-jk** [comment]
One more with the same issue.

**Comment by mercurykd** [comment]
One more with the same issue.

**Comment by NoremPload** [comment]
Same here :(

**Comment by GXGOW** [comment]
Yup, not working here either :/

**Comment by rahulnever2far** [comment]
@hajekj Thank you so much for fixing this. Could you please release the fixed version in the Marketplace.

**Comment by hajekj** [comment]
I am afraid I don't have enough permissions to publish the extension. I only have repo permissions. It is up to @lukasz-wronski to publish it.

**Comment by vyskoczilova** [comment]
Hi, any updates on this topic? Having the same issue.

**Comment by hajekj** [comment]
What we can do is to publish a second version of the extension - which would create more confusion amongst the users. Any ideas what to do?

**Comment by olivero86** [comment]
I'm still having this problem with the extension version 0.3.3?

**Comment by nok91** [comment]
Ftp-sync: no operations list to commit. Run sync first.

**Comment by Sominemo** [comment]
One more with the same issue.

**Comment by alextegelid** [comment]
I manually patched version 0.3.3 with pu #200 and it works fine again. I didn't dig any deeper to identify where the bug was introduced again though.

**Comment by YiiTing** [comment]
One more with the same issue.

**Comment by cammcnab** [comment]
Same issue here with latest extension version

**Comment by Yprolic** [comment]
Same issue

**Comment by junshipeng** [comment]
One more with the same issue.

**Comment by hajekj** [comment]
Please take a look at this addin, it is more integrated with VS Code and offers comparable functionality: https://marketplace.visualstudio.com/items?itemName=mkloubert.vscode-remote-workspace
