### ISSUE TITLE
Unable to upload a folder

### ISSUE THREAD

**Issue by providen-rob** [lukasz-wronski/vscode-ftp-sync#167]
Using version 0.3.3 on VSCode 1.12.1 with using SSH & key based auth..

When I upload a locally created folder that has an HTML file in it, I get:
`Ftp-sync: Uploading test failed: Error: Failure`
On the remote side, nothing.

If it's an empty directory I get: 
`Ftp-sync: Uploading testFolder failed: Error: EISDIR: illegal operation on a directory, read`
On the remote side there is an empty file created.

**Comment by kalieye** [comment]
fixed on the latest release which is not yet on the extension store though, if you want you can grab the latest github code

**Comment by providen-rob** [comment]
awesome, thanks!
