### ISSUE TITLE
Upload On Save

### ISSUE THREAD

**Issue by Wankishh** [lukasz-wronski/vscode-ftp-sync#168]
Upload on save don't work. It's fine but will be more efficient if works :)

**Comment by VickyKoblinski** [comment]
It's not working for me either.

VSC version: 1.12.1
ftp-sync version: 0.3.3
protocol: sftp

Tried it with passive true and passive false.

**Comment by Devnco** [comment]
Same here doesn't work either no matter what :-(

**Comment by trisztan** [comment]
Same here not working. Debug option not working.

**Comment by kalieye** [comment]
it's all fixed in the github release, unfortunately the vscode version is not yet updated with the patches!

**Comment by trisztan** [comment]
Little note:

1. I downloaded plugin.
2. Reboot VS
3. Set ftp config and enable debug and uploadOnSave.
4. Try save a simple.txt and not working.
5. f1 sync current file successfully uploaded.
6. Select php file edited and saved again not working. Try sync not working.

Solution: Set ftp connection and  restart VS and everything working.

**Comment by Wankishh** [comment]
Yeah, Works now! :) Thanks 👍

**Comment by kalieye** [comment]
yeah i forgot to mention that you need to reload the window for the new configuration to work!
