### ISSUE TITLE
not uploading (on save) to correct folder

### ISSUE THREAD

**Issue by ChazyTheBest** [lukasz-wronski/vscode-ftp-sync#17]
Maybe I'm doing something wrong, I don't know... I just created a folder and inside that folder I placed the configuration and the folders of each website (main domain, subdomain and framework folders). But when I save a file it auto uploads it creating the full path inside the folder where the file is.

For example, the path to a file is:

- ./static.website.com/js/scripts.js

But when I save the file it uploads it to:
- ./static.website.com/js/static.website.com/js/scripts.js

Why is this happening?

**Comment by lukasz-wronski** [comment]
If you'd log in with an FTP client what is the directory that you are in?

**Comment by ChazyTheBest** [comment]
The ftp account has access to "/home/user/", the server document root where all my domains/subdomains are stored. I'm currently using that account in notepad++ and i can see all the folders for each website.

**Comment by kevinclseifert** [comment]
I can confirm this aswell, it happens for me too when I press save or uses Local to Remote upload.

**Comment by lukasz-wronski** [comment]
@ChazyTheBest can you show me exactly how your ftp-sync.json file looks like (of course without ftp host, login and pass)?

**Comment by ChazyTheBest** [comment]
You mean the path? Is the default "./".

```json
{
    "remotePath": "./",
    "host": "",
    "username": "",
    "password": "",
    "port": 21,
    "uploadOnSave": true,
    "ignore": [
        "\\.vscode",
        "\\.git"
    ]
}

**Comment by lukasz-wronski** [comment]
Ok. Thanks for feedback.
