### ISSUE TITLE
If ignore regular expression is invalid, stuck at sync prepare in progress

### ISSUE THREAD

**Issue by crkellen** [lukasz-wronski/vscode-ftp-sync#172]
I was attempting to use ftp-sync as a replacement for Atom's remote_sync. I was have a lot of issues attempting to push anything from local to remote, but I found the issue.

I wanted to exclude any node_modules folders/files. So I copied the line I had from remote_sync:

"**/node_modules/**",
"**/node_modules/**/*"

This would cause the issues. Remove the lines, no issues, everything pushes as expected, however 10k+ operations is not ideal if I can do an npm install.

I eventually figured out that if I replace those two lines with:

"/node_modules/*"

It works as I want it to.
There was no error reporting as far as I could see and setting debug to true didn't help.

**Comment by MatthewGieger** [comment]
@crkellen Have you been able to find out how to ignore sub-directories? I've tried every combination of including slashes and asterisks that i could think of, all with no luck.

**Comment by crkellen** [comment]
As I said in the post, apparently that line worked for me.

What is your setup that you are attempting to push/ignore?

**Comment by MatthewGieger** [comment]
Oh, i didn't realize that was a subdirectory. Here's my ignore config:
 `
   "ignore": [
        "\\.vscode",
        "\\.git",
        "\\.DS_Store",
        "public_html/Gallery"
    ],`

**Comment by crkellen** [comment]
Mine looks like this:
```
    "ignore": [
        "\\[.]vscode",
        "\\[.]git",
        "\\[.]DS_Store",
        "\\[.]eslintrc.js",
        "/node_modules/*"
    ]
```

My directory structure is this:
ProjectDir -> .vscode, client, node_modules, src, {some files}

**Comment by MatthewGieger** [comment]
@crkellen Thanks for the details. I guess my problem is that i need to ignore subdirectories that are more than one layer deep like so:
`    "ignore": [
        "\\.vscode",
        "\\.git",
        "\\.DS_Store",
        "stats",
        "/public_html/Gallery/*",
        "/public_html/sermons/*"
    ]`

Neither the Gallery nor the sermons subdirectories are ignored. Any idea on those?

**Comment by crkellen** [comment]
Hmm. To be honest, I haven't really worked with this in some time. I'll see if I can figure anything out right now. Okay. I did that:

```
"ignore": [
        "\\[.]vscode",
        "\\[.]git",
        "\\[.]DS_Store",
        "\\[.]eslintrc.js",
        "/node_modules/*",
        "/client/js/*"
    ]
```
So I tested this:
1. Ctrl + Shift + P to open Command Palette
2. Typed "ftp" to find the command "ftp-sync: Local to Remote" (chose " '.' this directory"
3. Ran the command, a message pops up asking if I want to submit it now, or review
4. I chose review
5. Checked to see that there was files waiting to be submitted from './client/js/'
6. Edited ftp-sync.json in the .vscode folder to be as it is pasted above
7. Ran steps 1 - 4 again
8. No files were waiting to be submitted from ./client/js/'

So that should do it for you. What kind of files do you have in there?

**Comment by MatthewGieger** [comment]
@crkellen Wow man thanks for testing it out. I was just playing around and came to the same conclusion. I think i had my root directory messed up. I'm primarily filtering out .mp3 and .ogg files. I've got it working using:

> 

    "ignore": [
        "\\.vscode",
        "\\.git",
        "\\.DS_Store",
        "/Gallery/",
        "/js/*",
        "/css/*",
        "/fonts/*",
        "/extras/*",
        "/xmp3Player-mini/",
        "//*[.]mp3",
        "//*[.]ogg"
    ]

**Comment by crkellen** [comment]
Awesome, glad you could get it to work!
null

**Comment by MatthewGieger** [comment]
@lukasz-wronski I believe this issue can be closed.

**Comment by crkellen** [comment]
I agree that this issue can likely be closed. Hopefully if anyone else happens to have this issue, they can take a look at this issue.
