### ISSUE TITLE
Issue when uploading a non-existent file to the server

### ISSUE THREAD

**Issue by GeneralCan** [lukasz-wronski/vscode-ftp-sync#178]
hey,

trying to upload a new file to the server and I get:

Running the contributed command:'extension.ftpsyncuploadselected' failed.

the weird thing is that I am able to sync files already on the server, the issue is adding a new file

**Comment by kevinko12323** [comment]
Same problem here

**Comment by NajSurf** [comment]
Should be working fine after the fix #269
