### ISSUE TITLE
Pageant: How exactly do you configure agent to work?

### ISSUE THREAD

**Issue by NullPrice** [lukasz-wronski/vscode-ftp-sync#181]
Hello,

Having difficulty using this with the `agent` key set to `pageant`.

Basically it is throwing the error: `All configured authentication methods failed`. 

It does work fine if I use a path to an ssh key and hardcode the passphrase in. But I would prefer to use pageant as that is what I use for everything else.

I know pageant is working fine on my system as I can ssh in using Putty and use Filezilla for SFTP. 

Am I missing something?

My config:

```json
{
    "remotePath": "./Projects/****/",
    "host": "91.***.***.***",
    "username": "root",
    "port": 22,
    "protocol": "sftp",
    "uploadOnSave": true,
    "agent": "pageant",
    "ignore": [
        "\\.vscode",
        "\\.git",
        "\\.DS_Store"
    ],
    "generatedFiles": {
        "uploadOnSave": false,
        "extensionsToInclude": [],
        "path": ""
    }
}
```

**Comment by ArvinH** [comment]
Somehow the latest code didn't publish to VSCode marketplace, I supposed.

So just go check out your extension in `~/.vscode/extensions/lukasz-wronski.ftp-sync-0.3.3/`
You may see the code is not the latest one, if so, just add the related code you need in that foldr, it will work again.

I believe the code you should add is in this PR:
https://github.com/lukasz-wronski/vscode-ftp-sync/pull/134/files

Not sure our situation is same or not but this solved my problems on using agent.

**Comment by econgra** [comment]
Thanks, also solved my problem.
