### ISSUE TITLE
ignore option regex

### ISSUE THREAD

**Issue by xmoki** [lukasz-wronski/vscode-ftp-sync#182]
I'm really bad at regular expressions, and i just cant figure out how to ignore a root 'vendor' directory but not 'vendor' subfolders. Can someone help me?

**Comment by Frizz925** [comment]
Having the same problem with this too recently

**Comment by bonovan** [comment]
Hey guys, I believe regex is broken and submitted a fix https://github.com/lukasz-wronski/vscode-ftp-sync/pull/210. Hopefully it get's accepted!

**Comment by xmoki** [comment]
I forgot i had opened this issue, i'm using partial remotePath+'\\vendor' on ignore to achieve what i wanted, but it feels like a hack, there should be a better way to do this with regex.

**Comment by NajSurf** [comment]
Go check the latest merge for a fix.
