### ISSUE TITLE
Issues with self signed certificate

### ISSUE THREAD

**Issue by Sgtpanda** [lukasz-wronski/vscode-ftp-sync#194]
Hey,

I'm trying to use the extension but every time I try to sync I get error `Ftp-sync: sync error: Error: self signed certificate`, could you add a config option to allow self-signed certs?

Thanks

**Comment by welljsjs** [comment]
The same thing mentioned above still occurs in v0.3.3 for me. 
If you think I should open a new issue on this, let me know. 
I just didn't want to open a duplicate. 
My current configuration looks like so: 
```
{
    "remotePath": "/",
    "host": "[removed]",
    "username": "[removed]",
    "password": "[removed]",
    "port": 2122, 
    "secure": true,
    "secureOptions": {"rejectUnauthorized":false},
    "protocol": "ftp",
    "connTimeout": 10000,
    "pasvTimeout": 10000,
    "keepalive": 10000,
    "uploadOnSave": false,
    "passive": false,
    "debug": true
}
```
`Ftp-sync: sync error: Error: self signed certificate`
But I'm still getting the exact same error. 
I'm 100% sure this is not a server problem or failure. 
Any help is appreciated.

**Comment by Sgtpanda** [comment]
@welljsjs I'm pretty sure the changes that got merged were never actually uploaded to the version that you download from the VSCode site is why.

You need to go to `%USERPROFILE%\.vscode\extensions` (on windows at least) open the extension and replicate the changes in the pull request, i.e. Open up `modules/ftp-config.js` and add `secureOptions: config.secureOptions,` on the line after `secure: config.secure,`.

**Comment by welljsjs** [comment]
Whooo, that’s what I call a super fast reply. Thanks a lot! Unfortunately, I‘m on Mac, but I think I‘ll figure it out. 
I havent even tought about that. As VSCode tells me that I have v0.3.3 installed, I thought that version would be equal to the 0.3.3 on Github, which does not seem to be the case as you say. Any reason for that? 
Anyways, I‘ll try it out asap. Thanks again for the fast response!
