### ISSUE TITLE
Integration with git-ftp

### ISSUE THREAD

**Issue by MariusVatasoiu** [lukasz-wronski/vscode-ftp-sync#198]
Any news about git-ftp integration? This whould be an awesome feature.

**Comment by devinrhode2** [comment]
This extension may be our only hope for now... google search for ["git-ftp" site:marketplace.visualstudio.com](https://www.google.com/search?q="git-ftp"+site%3Amarketplace.visualstudio.com) has literally just 1 result - this extension
