### ISSUE TITLE
Local to remote "Full sync" error

### ISSUE THREAD

**Issue by maximedupre** [lukasz-wronski/vscode-ftp-sync#20]
Error: 
> Ftp-sync: sync error: Error: Could not delete maxwell/maxwell/package.json: No such file or directory

Steps to reproduce:

1. Ftp-sync: Local to remote
    - Folder: "."
    - Full-sync
2. Repeat step number 1

For some reason, when doing a "Full-sync" the second time, it tries to delete a file in a subdirectory that doesn't exists. "package.json" is located at "maxwell/package.json", not "maxwell/maxwell/package.json".

Here are my configs:

    {
        "remotePath": "./maxwell",
        "host": "192.168.2.7",
        "username": "pi",
        "password": "raspberry",
        "port": 21,
        "uploadOnSave": true,
        "ignore": [
    		"/.DS_Store",
            "/.vscode",
	    	"/node_modules"
        ],
        "passive": false
    }

I hope this is helpful! 

Cheers!

**Comment by lukasz-wronski** [comment]
What version of plugin you have installed?

**Comment by maximedupre** [comment]
@lukasz-wronski Should have mentioned that! The latest - 0.2.4.

**Comment by lukasz-wronski** [comment]
OK, I'll try to take a look on it in next few days. This might be related to #19.

**Comment by maximedupre** [comment]
@lukasz-wronski Perfect, thanks!

**Comment by lukasz-wronski** [comment]
Manwhile can you check if problem still occurs if you'll change your remotePath in config from `./maxwell` to just `/maxwell`?

**Comment by maximedupre** [comment]
@lukasz-wronski I tried, it doesn't work. "./maxwell" uploads the local project to "/home/pi/maxwell" on the server, whereas "/maxwell" uploads to "/maxwell".

**Comment by kevinjp** [comment]
I can confirm this is the case aswell for Remote to Local. 

Host, Username and Password isn't the same as below, since I wouldn't type that real info here.
The RemotePath is exact tho. I've tried removing the '.' and './' aswell, without any difference.

When I Remote to Local, I do see my files on the FTP under "Review" and Operations counter.
Same for Local to Remote, as described in this example.

The error it says is: 
> Ftp-sync: sync error: Error: The system cannot find the path specified.
```
{
    "remotePath": "./public_html/website_data/",
    "host": "ftp.example.com",
    "username": "user",
    "password": "pass",
    "port": 21,
    "uploadOnSave": true,
    "ignore": [
        "\\.vscode",
        "\\.git"
    ],
    "passive": false
}
```

**Comment by suuuunto** [comment]
@lukasz-wronski 

same here

**Comment by lukasz-wronski** [comment]
Is this something I've broke with new version or you don't know if it was a problem before?

**Comment by kevinjpetersen** [comment]
For me, this definitely wasn't a problem before the new update(s). Before I could atleast push and pull (With folder duplications, but it worked) now I can't do anything.

**Comment by lukasz-wronski** [comment]
Understood - I'll try to find what's the problem ASAP.

**Comment by lukasz-wronski** [comment]
It should work fine now... Sorry for trouble ;)

**Comment by kevinjpetersen** [comment]
@lukasz-wronski Works perfect now.. Thanks!

**Comment by suuuunto** [comment]
@lukasz-wronski Yes, great!

**Comment by vteivans** [comment]
this still happens to me when I try to sync remote to local ☹

**Comment by tearingItUp786** [comment]
I'm also experiencing this issue when I try to do Local to Remote. Remote to Local works like a charm though.

**Comment by ilanlal** [comment]
Hi same issue with my vscode,  (Local to Remote)
Changing remotePath  "/" or "./" didn't resolve that issue.
ftp-sync: 0.3.3
vscode: 1.11.2
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

Thanks.

**Comment by babalubas090** [comment]
Hi everyone! I discovered the solution of the issue!
Simply change the permissions of the folder that you locate on "remotePath" to 777

The upload will be done, and you wont get any errors!

**Comment by kevinjpetersen** [comment]
Well, that only took 2 years 😂😂 @babalubas090 😂😂 haha

But nice! Not sure if this plugin is outdated tho

**Comment by babalubas090** [comment]
I think it's working, I'm using it right now 😂😂

But if you got a better solution, please share with me, I'm trying to get together the best solutions for this kind of purpose..

**Comment by dchenault** [comment]
CHMODing a directory to 777, especially on a remote server is NEVER the fix...
