### ISSUE TITLE
Sync R2L does not delete folder

### ISSUE THREAD

**Issue by rittap** [lukasz-wronski/vscode-ftp-sync#21]
Using 0.2.6 on Windows (same behavior in 0.2.5), a folder on a separate drive will not delete when running FTP-Sync: Commit using sample Review file below.

It does delete the files within the folder. No error has been thrown, and it will be 'stuck' on that particular task.

```
{
    "_readMe": "Review list of sync operations, then use Ftp-sync: Commit command to accept changes",
    "filesToUpdate": [],
    "filesToAdd": [],
    "dirsToAdd": [],
    "filesToRemove": [
        "Wallpapers/4WrlaRZ.jpg",
        "Wallpapers/Twitterc0bb1b9.jpg",
        "Wallpapers/Windows_Insider_Desktop_E-1920x1080-HD.jpg"
    ],
    "dirsToRemove": [
        "Wallpapers"
    ]
}
```

**Comment by lukasz-wronski** [comment]
This is fixed and will be released today with 0.2.7 version.
