### ISSUE TITLE
uploadOnSave: true not working 1.19.3

### ISSUE THREAD

**Issue by mzsolt1** [lukasz-wronski/vscode-ftp-sync#227]
Version 1.19.3
Commit 7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba
Date 2018-01-25T10:36:34.867Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

I don't know what's the problem, but if I press Ctrl+Shift+P and I choose "Sync current file to Remote" option then it works! I received status message: ".... uploaded successfully! " but "uploadOnSave" option is true, then nothing happens.

What's the problem? What can I do?

**Comment by theznerd** [comment]
Check out this open issue - changing uploadOnSave for generatedfiles to false is a temporary work around. I'm going to look through the code today and see if I can generate a pull to fix this since the developer seems to have gone quiet.

https://github.com/lukasz-wronski/vscode-ftp-sync/issues/184#issuecomment-324174223

**Comment by theznerd** [comment]
Okay - I think the issue her is maybe documentation related. If you set uploadOnSave for GeneratedFiles, you also need to give it a path for your generated files. I'm assuming that this is the root path of the "folder" you're working in. I've set that and auto-upload on save started working again.

**Comment by mzsolt1** [comment]
Yes, If I set the path in "generatedFiles" then works. Thx

    "remotePath": "/var/www/mypath",
    "host": "",
    "username": "",
    "password": "",
    "port": 21,
    "secure": false,
    "protocol": "ftp",
    "uploadOnSave": true,
    "passive": true,
    "debug": false,
    "privateKeyPath": null,
    "passphrase": null,
    "ignore": [
        "\\.vscode",
        "\\.git",
        "\\.DS_Store"
    ],
    "generatedFiles": {
        "uploadOnSave": true,
        "extensionsToInclude": [],
        "path": "/var/www/mypath"
    }
