### ISSUE TITLE
generatedFiles not auto-uploading

### ISSUE THREAD

**Issue by abhijeetdeb** [lukasz-wronski/vscode-ftp-sync#231]
I am unable to use the generatedFiles option to auto-upload my Sass generated CSS files. The uploadOnSave is _true_ and only the files I directly edit are getting uploaded.

```
"generatedFiles": {
        "uploadOnSave": true,
        "extensionsToInclude": [".css", ".sass"],
        "path": "C:/projects/Project Name/"
}
```

Is this feature not working anymore?

I am using VS Code 1.20.1 with ftp-sync 0.3.3 in Windows 10.

**Comment by sujan-s** [comment]
Try the project path eg. `"/dist"` or `"/build"` instead of the complete path.

**Comment by abhijeetdeb** [comment]
@sujan-s Tried using the "/path-to-generated-file" and "/path-to-generated-file/" both. Didn't work :(

**Comment by sujan-s** [comment]
No, what I mean is, the project directory is considered as the root, so if your CSS is generated within the `C:/projects/Project Name/dist/css` directory, all you need to do is point it to `"path": "/dist/css"`, instead of `"path": "C:/projects/Project Name/dist/css"`.

**Comment by abhijeetdeb** [comment]
@sujan-s Sorry, I didn't explain properly. Let me explain what I'm doing.

My folder structure  is

project-name
-css
--sass
---_style.sass_
--_style.css_ (This file is the generated one)

I have used the following combinations so far..

`"path": "/project-name"`
`"path": "/project-name/"`
`"path": "/project-name/css"`
`"path": "/project-name/css/"`
`"path": "/css"`
`"path": "/css/"`

None of them worked. If I save the _style.sass_ file, it uploads fine but I have manually upload the compiled _style.css_ file every time!

**Comment by omgdracula** [comment]
How would I choose the root folder for the project? would I have to use ../ or just / or would I just leave the quotes blank? my style.css is generated in the root of the project and not a specific folder.

**Comment by NajSurf** [comment]
Check out the latest merge for a fix #270

**Comment by ItSoftwares** [comment]
Hello everyone, I'm still having problems with my generated css files.

My project structure is this:

ProjectName
----assets
--------css
------------index.css
------------index.map.css
--------scss
------------index.scss

And my ftp-sync.json:
`"generatedFiles": {
        "uploadOnSave": true,
        "extensionsToInclude": [".css", ".map"],
        "path": "/assets/css"
    }`

The .scss file is uploaded without any problems, but the generated files will not work, thanks in advance.

**Comment by wwwanyu** [comment]
I'm having same problem like @ItSoftwares 's
It will be awesome if this feature work, looking forward to use it, thank you.

**Comment by babar-waheed** [comment]
This works for me. I'm using webpack with a wordpress theme so that i can use next-gen javascript and bundle my libraries in to one file. 

So my src folder is on the root that has all javascript and sass however, i generate my css & js files into the theme folder directly. As soon as i save my source file (which are in the ignore list below), webpack re-generates the files and are automatically updated to the dev machine. I hope that helps.

<pre>{
    "remotePath": "./public_html",
    "host": "ubuntu",
    "username": "mm",
    "password": "mm",
    "port": 21,
    "secure": false,
    "protocol": "ftp",
    "uploadOnSave": true,
    "passive": false,
    "debug": false,
    "privateKeyPath": null, 
    "passphrase": null,
    "agent": null,
    "allow": [],
    "ignore": [
        "\\.vscode",
        "\\.git",
        "\\.DS_Store",
        "src",
        "node_modules",
        "package-lock.json", 
        "package.json", 
        "webpack.config.js" 
    ],
    "generatedFiles": { 
        "extensionsToInclude": [".js", ".css"], 
        "path": "wp-content/themes/flatsome-child/dist" 
    }
}</pre>

**Comment by Deystr0** [comment]
What if i have two folders, /assets/css and /assets/js where i put my genereted files from webpack?
