### ISSUE TITLE
FTP-Sync: Upload File/Folder uploads an empty file with the folder name

### ISSUE THREAD

**Issue by vallieresc** [lukasz-wronski/vscode-ftp-sync#235]
In the explorer, right click a folder, click FTP-Sync:  Upload File/Folder, the upload is successful (no errors) but the result is an empty file with its name matching the folder name at the upload location. The files in the folder are not found. 

I noticed the readme indicates "You can also upload a single file by right-clicking on it in the left menu and choosing the "Ftp-sync: Upload File" command.". Perhaps the folder feature was not fully implemented. Please review the upload folder functionality.

**Comment by NajSurf** [comment]
fixed in #264
