### ISSUE TITLE
If the Review file is changed, the Commit will not work

### ISSUE THREAD

**Issue by EthraZa** [lukasz-wronski/vscode-ftp-sync#25]
If I ask for Review an action and Commit it without touching the Review file, it will work. But if I change the Review file, like comment out a line so the file does not get deleted or something, it will fail with the followiong error:
~~~
Running the contributed command:'extension.ftpsynccommit' failed.
~~~

**Comment by lukasz-wronski** [comment]
It have to be a valid json file. I will add validation and suitable message.

**Comment by lukasz-wronski** [comment]
Added. Will appear on `0.2.9` tonight.
