### ISSUE TITLE
Ftp-sync: Cannot init ftp-sync without opened folder

### ISSUE THREAD

**Issue by PM-LEE** [lukasz-wronski/vscode-ftp-sync#250]
Ftp-sync: Cannot init ftp-sync without opened folder

**Comment by PM-LEE** [comment]
why~

**Comment by Barolo83** [comment]
Same problem 
Ftp-sync: Cannot init ftp-sync without opened folder

**Comment by Barolo83** [comment]
I'm sorry: I'm understanding right now that I had just to open the right folder...

 Sorry for the inconvenience...
