### ISSUE TITLE
[RFC] "whitelist" option

### ISSUE THREAD

**Issue by aleclarson** [lukasz-wronski/vscode-ftp-sync#254]
The opposite of the `ignore` option. Only paths listed in `whitelist` are crawled and synced.

Or is `allow` supposed to work this way?

**Comment by frobinsonj** [comment]
> Or is `allow` supposed to work this way?

Yes, see the [init section](https://github.com/lukasz-wronski/vscode-ftp-sync#ftp-sync-init):

> allow - An array of escaped regular expression strings specifying paths which are allowed. If nonempty, unless a path matches any of these regular expressions it will not be included in the sync. Default value is empty, implying everything is allowed.

**Comment by aleclarson** [comment]
It's been a while since I made this issue, but I recall something about `allow` was not working correctly. Anyway, I stopped using this extension. Sorry!
