### ISSUE TITLE
SFTP?

### ISSUE THREAD

**Issue by keeross** [lukasz-wronski/vscode-ftp-sync#26]
Are there any plans on support of SFTP/SCP?

**Comment by lukasz-wronski** [comment]
This is a good idea. I'll put it into backlog. If there will be more people asking then I try to implement it.

**Comment by flobrflo** [comment]
Hey!
I just instal your great module for VC!
SFTP will be a good idea! :+1:

**Comment by cwramsey** [comment]
Consider this a second request then :+1:  I'd love to use VSCode more for work, but having to manually upload files is the pits.

**Comment by lukasz-wronski** [comment]
Thanks for feedback guys. I will definitely look into it in next few days...

**Comment by lukasz-wronski** [comment]
@flobrflo, @cwramsey, @keeross: I have first version of sftp support almost ready on branch v3.0. I will need a sftp server to test it now. Can anyone provide an account?

**Comment by stevelot** [comment]
Hey lukasz. I like your plugin a lot and sftp would be a nice extra. Check out filezilla server for sftp, but be carefull with the addware if you install it from sourceforge.

**Comment by lukasz-wronski** [comment]
Filezilla server does not support sftp, but I've found out that pretty much any ssh access can be used as SFTP so no worries guys - I'm on my way to test it..

**Comment by lukasz-wronski** [comment]
Done. Can be tested in `0.3.0`

**Comment by flobrflo** [comment]
Hey!
Sorry for late,
i just test your sftp update and it's work like a charm =)

Thank you ^^

**Comment by isaozler** [comment]
hey @lukasz-wronski any plans for privateKey connection support?

**Comment by lukasz-wronski** [comment]
Hi @isaozler, I'd like to do that if it's missing. Can you create separate ticket for it with info about how you'd like it to work?

**Comment by lv7777** [comment]
i want sync with scp.
and I find mention `I have first version of sftp support almost ready on branch v3.0.` 
I look forward to this feature !

@lukasz-wronski 
`Can anyone provide an account? `
BTW,  I can provide server.
do you want ssh key?

**Comment by perfecto25** [comment]
would love to have SCP option, FTP is such pain in ass to setup and configure + security issues
