### ISSUE TITLE
generatedFiles not work

### ISSUE THREAD

**Issue by patrick-abc** [lukasz-wronski/vscode-ftp-sync#260]
I have defined

> "port": 22,
>     "secure": true,
>     "protocol": "sftp",
>     "uploadOnSave": true,
>     "passive": false,
>     "debug": true,
>     "privateKeyPath": null,
>     "passphrase": null,
>     "agent": null,
>     "allow": [],
>     "ignore": [
>         "\\.vscode",
>         "\\.git",
>         "\\.DS_Store",
>         "\\assets"
>     ],
>     "generatedFiles": {
>         "uploadOnSave": true,
>         "extensionsToInclude": [".css"],
>         "path": "/"
>     }

My .scss files are in the folder /assets. The grunt process generate the .css file in Root.
When I change a .scss file in /assets the file (root of the project)/style.css was changed but ftp-sync was not detecting it (and it was not uploading).

**Comment by patrick-abc** [comment]
Nope. I changed to:
```
"port": 22,
    "secure": true,
    "protocol": "sftp",
    "uploadOnSave": true,
    "passive": false,
    "debug": true,
    "privateKeyPath": null,
    "passphrase": null,
    "agent": null,
    "allow": [],
    "ignore": [
        "\\.vscode",
        "\\.git",
        "\\.DS_Store",
    ],
    "generatedFiles": {
        "uploadOnSave": true,
        "extensionsToInclude": [".css"],
        "path": "/"
    }
```
but no effect. Grunt was generate a new style.css in the Root of project folder, but this .css was not loading up to FTP.

**Comment by NajSurf** [comment]
Check the new version on the marketplace. It should fix your problem. Also check #269 for more specific information.

**Comment by patrick-abc** [comment]
Sorry my late reply (year-end stress). Actually version for me still does not work. I have added the \assets folder to ignore list. Grunt generate the file in assets, in config.rb I move the file to the root of project. Could the mistake be there?
Side remark: I think with the new plugin version the ftp upload was not as stable as the older one. It happens every now and then; statusbar was write "..was uploading" and doesn't close. When I save the file another time, the upload works.
