### ISSUE TITLE
SFTP PrivateKey Support

### ISSUE THREAD

**Issue by isaozler** [lukasz-wronski/vscode-ftp-sync#28]
Hi @lukasz-wronski,

Do you guys planned to add a privateKey key in ftp-sync.json?

`"privateKey":"/here/is/my/key"`

something like this would fix this I guess 

`privateKey: require('fs').readFileSync('/here/is/my/key')`

**Comment by lukasz-wronski** [comment]
Thanks for your request. I guess I can add it easily, just need to check if my sftp library supports it.

**Comment by isaozler** [comment]
ssh2 @ npm does

**Comment by lukasz-wronski** [comment]
Cool, that's the one I'm using so I'll definitely add this to extension soon...

**Comment by isaozler** [comment]
Thanks @lukasz-wronski this would help working with @microsoft /vscode synchronously on aws projects

**Comment by frux** [comment]
+1! There is no extension with normal sftp supporting yet. Please add this feature!

**Comment by lukasz-wronski** [comment]
@isaozler, @frux: You can test it now in `0.3.1` version of extension, `privateKeyPath` parameter can be added to config file.

**Comment by isaozler** [comment]
it works, wunderbar :) :+1:

**Comment by ransoni** [comment]
Does it have support for password protected private keys?

**Comment by SyntaxErrol** [comment]
Note to Windows peeps about what wasn't immediately obvious:
- Using PuTTYgen, you want to export your private key in OpenSSH format.
- Passphrases don't seem to be supported.
- `"privateKeyPath"` backslashes need to be escaped, like so: `"C:\\Users\\username\\.ssh\\private_key_file"`

**Comment by sotirosn** [comment]
The above comment needs to be put in the readme file.  It has taken me hours to find it.

**Comment by smedsrud** [comment]
adding support for "passphrase": would do the trick

**Comment by darkflame470** [comment]
It gets stuck on "sync prepare in progress" when you use an ed25519 key. Might want to put that it only supports RSA keys.

**Comment by raimis001** [comment]
Its posible use .pem file for privateKeyPath?
