### ISSUE TITLE
Running the contributed command:'extension.ftpsyncinit' failed.

### ISSUE THREAD

**Issue by kkop** [lukasz-wronski/vscode-ftp-sync#3]
>ftp-sync: init 
casues following error:
"Running the contributed command:'extension.ftpsyncinit' failed."

**Comment by lukasz-wronski** [comment]
Hi, thanks fo report. Can i get screenshot of how your files tree looks like? What OS do you use?

**Comment by kkop** [comment]
Windows 10. 
It's a wordpress (wooCommerce) shop, so quite many files and folders
![przechwytywanie](https://cloud.githubusercontent.com/assets/16068492/11457174/560597c4-96a2-11e5-8794-776dfe8c0843.PNG)

**Comment by lukasz-wronski** [comment]
Ok. I'll try to reproduce it. Thanks.

**Comment by kasik96** [comment]
Same problem. But if i select FTP Upload, is upload only folders, but nothing in it. I sync to empty folder. 
![screen shot 2015-12-02 at 13 14 36](https://cloud.githubusercontent.com/assets/7235992/11530644/aa700ab4-98f6-11e5-9764-1e065cf06c39.png)

**Comment by EthraZa** [comment]
Not sure if something related, just reporting here.
I saw "Running the contributed command:'extension.ftpsyncinit' failed." in two occasions:

1- If I choose "ftp-sync: init" and the file ftp-sync.json already exists.
2- When I configured the wrong path on "remotePath". (Can't recall the operation that triggers the error though. Maybe Sync R2L, synce the path wold not exist.)

**Comment by Sibyl-lsl** [comment]
您好，我现在也遇到这个问题；Running the contributed command:'extension.ftpsyncinit' failed.，这个问题应该怎么解决？

**Comment by dschiller** [comment]
Any Solutions ?

**Comment by JOZECN** [comment]
就vscode遇到此报错提示的处理方法：当前vscode窗口还没有打开工作文件夹，先打开工作文件夹之后再去对FTP配置文件进行初始化配置，就不会报错了，亲测，3.0.0+版本均测试
