### ISSUE TITLE
FTPS (FTP over SSL) support

### ISSUE THREAD

**Issue by MinimalDigital** [lukasz-wronski/vscode-ftp-sync#30]
Are there any plans to support FTPS (FTP over SSL) connections?

**Comment by lukasz-wronski** [comment]
It should support FTPS already.. isn't it?

**Comment by MinimalDigital** [comment]
Ah that's great if it does. I hadn't seen any reference to FTPS (FTP over SSL) in the readme, version history or GitHub issues. Only SFTP (Secure File Transfer Protocol) seems to be mentioned (and supported). I don't have the ability to test it myself just yet so I thought I'd ask the question.

Also thanks for the quick response!

**Comment by lukasz-wronski** [comment]
AFAIK the library I use for FTP supports FTPS without any problems as this
is the same protocol in terms of communication... Can anyone confirm it
works fine?

pt., 12.02.2016, 00:13 MinimalDigital użytkownik <notifications@github.com>
napisał:

**Comment by KooiRUG** [comment]
Ftps doesn't work here, sorry.

**Comment by lukasz-wronski** [comment]
@KooiRUG, can you show me your config (without sensitive data)?

**Comment by KooiRUG** [comment]
@lukasz-wronski yep, here it is:
```
{
    "remotePath": "/my/path",
    "host": "nicon.nl",
    "protocol": "ftp",
    "port": 21,
    "secure": true,
    "password": "****",
    "username": "****", 
    "uploadOnSave": true,
    "passive": true,
    "debug": false,
    "ignore": [
        "\\.vscode",
        "\\.git"
    ]
}
```
And this is how it shows up in my ftp-server:
```
(000143)2/14/2016 16:04:11 PM - (not logged in) ([ip])> 220----------------------------------------------------------
(000143)2/14/2016 16:04:11 PM - (not logged in) ([ip])> 220- This is NICons FTP-server. We only allow sftp/ftps
(000143)2/14/2016 16:04:11 PM - (not logged in) ([ip])> 220 ---------------------------------------------------------
(000143)2/14/2016 16:04:11 PM - (not logged in) ([ip])> USER ****
(000143)2/14/2016 16:04:11 PM - (not logged in) ([ip])> 530 This server does not allow plain FTP. You have to use FTP over TLS.
(000143)2/14/2016 16:04:11 PM - (not logged in) ([ip])> disconnected.
```
In other words, no tls-attempt is made (no `AUTH TLS` command is sent).  
But then again, may be my config is all wrong?

**Comment by lukasz-wronski** [comment]
@KooiRUG: Is this a correct port for FTPS connection? Shouldn't you use port 990?

**Comment by KooiRUG** [comment]
@lukasz-wronski Port 21 will do (explicit over SSL/TLS shares its port with the regular ftp-port), port 990 is for an implicit connection. Tried that too, but using port 990, we're not going beyond:

`(000158)2/14/2016 17:38:47 PM - (not logged in) ([ip])> Connected on port 990, sending welcome message...`

To be sure implicit connections work @ my server, I connected using another application:
```
(000159)2/14/2016 17:40:58 PM - (not logged in) ([ip])> Connected on port 990, sending welcome message...
(000159)2/14/2016 17:41:04 PM - (not logged in) ([ip])> SSL connection established
(000159)2/14/2016 17:41:06 PM - (not logged in) ([ip])> USER ****
(000159)2/14/2016 17:41:06 PM - (not logged in) ([ip])> 331 Password required for ****
(000159)2/14/2016 17:41:07 PM - (not logged in) ([ip])> PASS ****
(000159)2/14/2016 17:41:07 PM - **** ([ip])> 230 Logged on
```

**Comment by AdrienCasagrande** [comment]
In modules/ftp-config.js .getSyncConfig doesn't return any 'secure' option. So node-ftp always use the default false value.

```
getSyncConfig: function() {
		var config = this.getConfig();
		return {
			local: config.localPath,
			remote: upath.toUnix(config.remotePath),
			host: config.host,
			port: config.port,
			user: config.username,
			password: config.password,
			**secure: config.secure,**
			ignore: config.ignore,
            passive: config.passive,
            protocol: config.protocol || "ftp",
            privateKeyPath: config.privateKeyPath,
            debug: config.debug ? function(msg) {
                output(msg);
            } : null
		}
```

**Comment by devmount** [comment]
Is there any solution? My provider only allows FTP over TLS...

**Comment by Feday** [comment]
Hello there, I also confirm that cannot use FTP over SSL

**Comment by hajekj** [comment]
Hey guys, created a pull request in order to enable the support (successfully tested it also).

**Comment by MinimalDigital** [comment]
Is there any chance of this being added to the next release?

**Comment by bholmes451** [comment]
I'm interested in using this also.  I have been using Filezilla but attempting to streamline my dev process currently and I liked this ftp plugin for vscode better than the other one :-)

**Comment by michalhudecek** [comment]
Any progress on this? We are forced to use FTPS on our server.

**Comment by hajekj** [comment]
This is now resolved and #62 is merged into master.

**Comment by FahadAli-Khan** [comment]
"port": 21,
 "secure": true,
 "protocol": "ftpes",
  "secureOptions": {"rejectUnauthorized": false},
This works fine for me

**Comment by cfmx** [comment]
> "port": 21, "secure": true, "protocol": "ftpes", "secureOptions": {"rejectUnauthorized": false}, This works fine for me

+1
