### ISSUE TITLE
ftp-sync.son don't ignore folder on mac

### ISSUE THREAD

**Issue by schillermann** [lukasz-wronski/vscode-ftp-sync#34]
This syntax don't ignore my folder on the mac.
 
```
{
"ignore": [ "\\.vscode" ]
}
```

**Comment by tory37** [comment]
I am on windows, and it seems this doesn't work for me either.  
`"ignore": [
        "\\.vscode",
        "\\.git"
    ]`

**Comment by tory37** [comment]
I did this, `"ignore": [
        ".vscode",
        ".git"
    ] ` and it successfully ignores the directories.

**Comment by schillermann** [comment]
That's right. This work on mac `"ignore": [ ".vscode", ".git" ]` 

If i select the option "Ftp-sync: Local to Remote" then i see all folders and files, also ignored.
That has confused me.

**Comment by sbryfcz** [comment]
Hmmmm. So it seems that the sync only ignores local files (with the ignore setting). My problem is that I dont want node_modules sync either way. But it looks like this extension is still reading all the node_modules on the remote server. Does that make sense?

**Comment by suuuunto** [comment]
I got the same problem.

> So it seems that the sync only ignores local files (with the ignore setting). My problem is that I dont want node_modules sync either way. But it looks like this extension is still reading all the node_modules on the remote server. Does that make sense?
