### ISSUE TITLE
SSH agent support

### ISSUE THREAD

**Issue by mattrat** [lukasz-wronski/vscode-ftp-sync#35]
It would be really helpful if the was support for an SSH agent so the SSH key passphrase is not stored in a file.

**Comment by eoli3n** [comment]
would be great +1

**Comment by WORMSS** [comment]
Just adding my +1 to this. hopefully @lukasz-wronski  is listening.

**Comment by hajekj** [comment]
Just merged this to master.

**Comment by jsmilovic** [comment]
PR #134
