### ISSUE TITLE
ftp-sync on mac - not closing connection

### ISSUE THREAD

**Issue by bobbynishi** [lukasz-wronski/vscode-ftp-sync#4]
When syncing directory or "on save", ftp connection appears doubled on server side (using goDaddy cPanel) and they immediately switch to idle.

Every new ftp servers seems to be doing the same.  I end up with several connections open until I get denied (421) new connections.

**Comment by lukasz-wronski** [comment]
Right now I'm working on rewriting ftp-sync engine (till now it's using ftp-sync library which have some issues). I will focus on ftp connections management to avoid such situations.

**Comment by bobbynishi** [comment]
Thank you.  I can't tell you how much I appreciate your work!

I am looking forward to the next release!

**Comment by lukasz-wronski** [comment]
@bobbynishi this is fixed in new version (0.2.0). You can test if it works okay now. Thanks.

**Comment by bobbynishi** [comment]
Tested it.  Works!  Awesome!  Thank you!
