### ISSUE TITLE
is there a way to except some files on download remote to local?

### ISSUE THREAD

**Issue by rico345100** [lukasz-wronski/vscode-ftp-sync#42]
hi, i am using this extension well, and i have one question.
i want to download files from server except some files(like node_modules) so i added "ignore" options in ftp-sync.json file, but it didn't work. looks like "ignore" option is for exclude uploading files on sync. i couldn't found any information about them. is there a way to except some files on download? if no, i hope that you make this and this will very handy for other people who use your plugin.

**Comment by rico345100** [comment]
solved.

**Comment by alvise** [comment]
Can i ask you how you solved?

**Comment by rico345100** [comment]
@alvise In my case, I just removed node_modules before download it to local machine, because node_modules can easily installed by "npm install" in remote server. After download ends, I installed node_modules again and it solved.

**Comment by alvise** [comment]
Thanks, i solved side-loading version 0.3.2 and excluding some folders. (I found that i needed to use absolute path for the ftp to male it work "/" and not "./")
