### ISSUE TITLE
First tests with ftp-sync 0.2.0

### ISSUE THREAD

**Issue by EthraZa** [lukasz-wronski/vscode-ftp-sync#5]
1- Sync (L2R or R2L) always shows 0 operations. The Review file comes with all the operations with empty arrays.

2- Force download or upload, I believe, are showing the right number of operations, if I just ask to Run, it is not working with the error:
~~~
Ftp-sync: sync error: Error: EXDEV: cross-device link not permitted, rename '/tmp/uf58xa20tz9f6r' -> '/PATH/FileName.js'
~~~
(My /home is mounted in another partition then my /, so my /tmp is in a cross-device regarding anything on /home)

3- After some tryes the Review file stopped to work, it is not been generated anymore, even after I close and reopen VSCode.

4- Would be possible to when we ask for any operations, the dropdown to choose the directory, to already come inside the folder of the file we are editing?

5- Question: If I need to tell if I want the sync to L2R or R2L is it still a "sync"? I'm asking because I woud assume if I ask for sync, it would detect what needs to go R2L and what needs to go L2R.

6- Upload On Save is still working ok.

7- I like the possibility to Run (N operations), Review, Cancel. This will be easily the best ftp plugin for VSCode.

**Comment by lukasz-wronski** [comment]
@EthraZa  

Hi, I splited it into smaller issues. 
Regarding number 5 - do you mean there should be a third option to sync both ways?
