### ISSUE TITLE
Upload single file feature

### ISSUE THREAD

**Issue by adebali** [lukasz-wronski/vscode-ftp-sync#53]
It would be nice to have the enhancement of uploading a single file.

**Comment by Sachelis** [comment]
I agree. The number of keystrokes (e,g, F1, type "ftp-", scroll down to "Local to Remote", select a folder, etc) after changing one or two files is too much. I'd like to see a "FTP this file" command in a file's shortcut menu. I'd also love to see a "Repeat the last ftp-sync task" shortcut key, which would remember the last task (upload/download), the last folder, the last Full-Sync/Safe-Sync, etc settings.

This is a great extension, Lukasz!

**Comment by HansLanger** [comment]
Using a normal FTP is faster than using this plugin UNLESS it can upload on save a changed file.

**Comment by ufoloko** [comment]
You can use the option upload on save, this will upload just a file when you work in works great !!

**Comment by memmaina** [comment]
This feature is Needed Soon!

**Comment by rmevans9** [comment]
This actually looks pretty straight forward to implement. I will see about doing a PR in the next few days.

**Comment by rmevans9** [comment]
Or I will just knock it out tonight...ha!
