### ISSUE TITLE
Regex not matched properly

### ISSUE THREAD

**Issue by QewQew** [lukasz-wronski/vscode-ftp-sync#54]
I'm trying to ignore files with certain extensions, in this case: *.o files.
This is my ignore list:

```
    "ignore": [
        ".*\\.o"
    ]
```

However, the files still appear in the review page.
I've also tried without escaping the `.`, however that matches everything with an `o` in it, since the regex will treat the `.` as any character.

Am I doing something wrong? From the code, it does look like it's using regex to match file names.

**Comment by Sachelis** [comment]
First, Lukasz, this is a GREAT extension! I hope you haven't given up on it. A good ftp extension is critical to Visual Studio Code.

As for the regular expressions, I'm having the same problem as QewQew. Setting ignore to ".*psd" will ignore all files ending with "psd", but ".*\\.psd" (which should ignore all files ending with ".psd") doesn't ignore any of them.

As a side note, I can't added comments to the "init" structure (i.e., add // comments in ftp-sync.json). When I do, I get the message, "Running the contributed command:'extension.ftpsyncupload' failed.").

**Comment by QewQew** [comment]
@Sachelis JSON doesn't natively support comments. That's why an actual field is used in the sync reviews.

**Comment by brouwerQ** [comment]
How can you exclude a certain extension?

**Comment by SynCap** [comment]
I seems that proper escaping of regexp dot rule works only at start of string:
```
    "ignore": [
        "\\.vscode",	//works
        "\\.idea",		//works
        "\\.phpintel",	//works
        "\\.git",		//works
        "\\.DS_Store",	//works
	"desktop\\.ini",	//don't works
	"desktop.ini",	//works ?
	"Thumb.db",	//works ?
        "\\.editorconfig",	//works
        "sftp-config",		//works, but all - not only needed "sftp-config.json"
        ".less"		//works improperly - also ignore such as "simpless_file.txt"
    ]
```
For skipping "*.less" files I forced to use "^css/.*less$", but no way to set simple mask for certain extension, which can be applied through workspace.

**Comment by bonovan** [comment]
Hey guys, I believe regex is broken (all instances of \ are converted to /). Submitted a fix https://github.com/lukasz-wronski/vscode-ftp-sync/pull/210. Hoping it is accepted.

**Comment by sotirosn** [comment]
It seems that ftp-sync wants to ignore all hidden file on the host, (.* files).  So I cannot download .gitignore.   If however I change \\.git to \\.git$ then I can upload the .gitignore but it will want to be removed if I then sync from Remote to Local.  If I remove \\.git entirely I still am unable to download .gitignore and surprisingly unable to download the .git folder.

**Comment by NajSurf** [comment]
Go check the latest merge for a fix. Should be working fine from now on.

**Comment by geerdes** [comment]
I got it work on Windows by using 
`"./*[.]log"`
Hope this helps. Any .log file is exluded
