### ISSUE TITLE
More like a question.

### ISSUE THREAD

**Issue by dulob** [lukasz-wronski/vscode-ftp-sync#56]
How to configure the ftp server? I have a ftp server with TLS and I can't connect to server with ftp-sync. it keeps showing  "Ftp-sync: Uploading file.js failed: Error: TLS required". How the TLS is configured?

**Comment by SgtOddball** [comment]
Can I just ask what sort of certificate is your server using? Is it a self signed certificate or an CA verified certificate?

**Comment by SgtOddball** [comment]
I've had a further look into this and saving the certificate locally doesn't help with this.

**Comment by dulob** [comment]
it a self signed certificate.

**Comment by SgtOddball** [comment]
In that case, it's not something that works at the moment. I've tried a few different things myself and they all fail.

**Comment by dulob** [comment]
Does it mean that a bug report should be opened?

**Comment by hajekj** [comment]
This appears to have been fixed with #62 (add support for FTPS), if the issue still persists, please reopen the issue.
