### ISSUE TITLE
Error: EXDEV: cross-device link not permitted on mounted drive

### ISSUE THREAD

**Issue by lukasz-wronski** [lukasz-wronski/vscode-ftp-sync#6]
Force download or upload, I believe, are showing the right number of operations, if I just ask to Run, it is not working with the error:

    Ftp-sync: sync error: Error: EXDEV: cross-device link not permitted, rename '/tmp/uf58xa20tz9f6r' -> '/PATH/FileName.js'

(My /home is mounted in another partition then my /, so my /tmp is in a cross-device regarding anything on /home)

Reported by @EthraZa

**Comment by EthraZa** [comment]
Just saw this on 0.2.1 when Sync R2L

**Comment by rittap** [comment]
Still open in 0.2.5 using Sync R2L using Windows with two disks (VSCode runnning from C:\, work directory on D:\).

**Comment by lukasz-wronski** [comment]
So two partition causes this too? Thats good, I can easily test it and try to fix it. Thanks for info @rittap.

**Comment by lukasz-wronski** [comment]
This is fixed now. Please check if the problem still exists.

**Comment by rittap** [comment]
Confirmed fix for Windows. Will check on Mac OS X tomorrow. Perhaps @EthraZa can verify for Linux?

**Comment by EthraZa** [comment]
Fixed on Linux as well.

Great! Thank you.
