### ISSUE TITLE
using less for css does not sync recompiled css

### ISSUE THREAD

**Issue by sbsrouteur** [lukasz-wronski/vscode-ftp-sync#65]
Hi,

Is there a way/config to tell ftp-sync that some files need to be updated as well?

Using less, my css gets recompiled at each update of the .less, but the extension only updates the less file upon save.

**Comment by sagive** [comment]
i think a simple approach would be to upload the same file name with different extensions aka some-styles.css / some-styles.less  or for example  some-scripts.js  /  some-scripts.min.js.

**Comment by jsmilovic** [comment]
Should be closed by #118
