### ISSUE TITLE
Upload on save and sass compiled files

### ISSUE THREAD

**Issue by wojtek1150** [lukasz-wronski/vscode-ftp-sync#71]
Hello ;)

Firstly I must say that very well work. But I found a big problem for me. I'm using grunt to compile sass and js files. And when You save *.sass file it will be uploaded to server, then watch compile my file. It create *.css file but that file isn't uploaded. Your plugin is hooked only on save, but I (and I think many peoples too) to watch folder for changes and remote upload after any file changed/added.

Can You add this?

Greetings, W

**Comment by jsmilovic** [comment]
Should be resolved by #118
