### ISSUE TITLE
encrypted private key detected but no passphrase given

### ISSUE THREAD

**Issue by mitralone** [lukasz-wronski/vscode-ftp-sync#81]
When your private key has a passphrase, the connection simply fails. To fix, I made the following change to sftp-wrapper.js

client.connect({
            host: ftpConfig.host,
            port: ftpConfig.port,
            username: ftpConfig.user,
            password: ftpConfig.password,
            **passphrase: ftpConfig.password,**
            privateKey: privateKey
        });

I made the ftpConfig.password to be used as the passphrase. You just need to put your passphrase as the password in the ftp-sync.json file. It works.

**Comment by smedsrud** [comment]
in /modulessftp-wrapper.js add passPhrase: ftpConfig.passPhrase in client.connect()
in /modules/ftp-config.js add passPhrase: config.passPhrase, in getSyncConfig: function()

**Comment by hajekj** [comment]
This appears to be fixed in the newer releases. Please reopen this ticket if you are still experiencing this issue.
