### ISSUE TITLE
Auto Compiled File not Syncing

### ISSUE THREAD

**Issue by sammytapa** [lukasz-wronski/vscode-ftp-sync#83]
Hi,

I use Prepros for compiling my sass files. I set 'uploadOnSave' => true, but the compile css is not syncing on the remote server when I save my updated sass file. Locally the css is updated but it is not uploading on remote host. Can you add this feature in next release?

Thanks

**Comment by wojtek1150** [comment]
+1

**Comment by dakolech** [comment]
+1

**Comment by ZanderBrown** [comment]
@wojtek1150 & @dakolech If your going to +1 why don't you use the +1 reaction?

**Comment by mikoSTAR** [comment]
+1

**Comment by przemkow** [comment]
+1

**Comment by mattmcleod** [comment]
I'm similarly using grunt from the task-runner to auto-compile LESS to CSS. It'd be awesome if there were some way to get the results to auto-upload.

Maybe an explicit list of files to watch?

**Comment by dallanlee** [comment]
I would really like this feature as well.

I'm coming from Atom and used https://github.com/mgrenier/remote-ftp which had an option for an array of files to be "watched."

I would love this same functionality.

**Comment by rewphus** [comment]
+1

**Comment by sagive** [comment]
+1

**Comment by jsmilovic** [comment]
Should be resolved by #118
