### ISSUE TITLE
collecting remote files list (even when its in ignore list)

### ISSUE THREAD

**Issue by ole1986** [lukasz-wronski/vscode-ftp-sync#86]
I noticed that remote files are being collected even when I set the whole directory into the  ignore list using ftp-sync.json -> ignore property.

Because of this I also think it sporadically crashes the visual studio code window

**Comment by joas8211** [comment]
I think the ignore property does only effect local files.
Something like that for remote files would prevent crash if you ignored the folder that's too large to handle.

**Comment by hajekj** [comment]
#84 was merged into master, should be resolved now.
