### ISSUE TITLE
Sync (L2R or R2L) always shows 0 operations.

### ISSUE THREAD

**Issue by lukasz-wronski** [lukasz-wronski/vscode-ftp-sync#9]
Sync (L2R or R2L) always shows 0 operations. The Review file comes with all the operations with empty arrays.

This might be related to #6 
Reported by @EthraZa

**Comment by lukasz-wronski** [comment]
Can you check if those problem still exists in `0.2.6`. I'm having trouble with reproducing it?

**Comment by lukasz-wronski** [comment]
@EthraZa: Can you check if those problem still exists in `0.2.6`. I'm having trouble with reproducing it?

**Comment by EthraZa** [comment]
I did some tests and it seens to be working as expected now.

Thank you.
