### ISSUE TITLE
Folders always to sync on file save

### ISSUE THREAD

**Issue by mikoSTAR** [lukasz-wronski/vscode-ftp-sync#93]
Hi,

I would like to choose a folder in which ftp-sync should always look for changes on any file save..
Would it be possible?

I have a situation where I save .scss files for styles and than grunt generates css files based on that.
.scss files are synced than but I need also those generated .css files by grunt to be sync as well in order to see changes on website.

**Comment by aut0poietic** [comment]
Must second (third? fourth?) generated files are uploaded when, uh... generated. Wouldn't object to a "watch"-list of files that are monitored by the file system, if that helps make this feature easier to implement. 

Must say: This extension is pretty awesome. Thanks for your work.

**Comment by jsmilovic** [comment]
#118 should resolve this

**Comment by aut0poietic** [comment]
Thanks @jsmilovic. I've added `"generatedFiles": {}` to my `ftp-sync.json` in anticipation of the feature. ;-)
